zegl/kube-score

README.md
=> doc(readme)

README.md
Signed-off-by: Johannes M. Scheuermann <joh.scheuer@gmail.com>
=> Add docs for installation

README.md, cmd/kube-score/main.go, score/container.go, score/score.go, score/score_test.go, score/testdata/pod-test-resources-limits-and-requests-no-cpu-limit.yaml
=> cmd: add flag to disable requirement of seting a CPU limit

README.md, cmd/kube-score/main.go, scorecard/scorecard.go
=> cmd: add --output-format flag that can toggle human or ci friendly output

score/score.go, score/score_test.go, score/testdata/configmap-multi-dash.yaml
=> score: split on --- only in the begining of a line

score/score.go, score/service/service.go, score/service_test.go, score/testdata/service-type-clusterip.yaml, score/testdata/service-type-default.yaml, score/testdata/service-type-nodeport.yaml
=> service: advice against use of nodeport services

score/cronjob/cronjob.go, score/cronjob_test.go, score/score.go, score/testdata/cronjob-deadline-not-set.yaml, score/testdata/cronjob-deadline-set.yaml
=> cronjob: add a check for having startingDeadlineSeconds set

cmd/kube-score/main.go
Scoring is no longer performed when executing "kube-score file.yaml", "kube-score score file.yaml" must always be used.
kube-score no longer panics if a file could not be opened, an error is returned and handled in a nicer way.
Fixes #115
Fixes #116
=> cmd: remove backwards compatible scoring, improved error handling

cmd/kube-score/cmd_version.go, cmd/kube-score/main.go
The version information is added automatically by goreleaser
Fixes #119
=> cmd: add version sub-command

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/bug_report.md, README.md
The issue template has also been slightly modified
=> github: update contributing guidelines

score/probes/probes.go
This is an obvious extension of the original idea that somehow I forgot.
=> ignore probes for jobs

score/checks/checks.go, score/meta/labels.go, score/meta/labels_test.go, score/score.go, score/stable/stable_version.go
This fixes #130
```
RELNOTE: Add check that validates label values
```
=> score: add a check that validates label values

README_CHECKS.md
```
RELNOTE: Add check that validates the value of labels
```
The relnotes are have been added to this PR, as they where forgotten in #135
=> docs: generate README_CHECKS.md

score/ingress/ingress.go
```
RELNOTE: Add support for named ports in the ingress-targets-service check
```
=> ingress: add support for named ports

README_CHECKS.md, domain/kube-score.go, parser/parse.go, score/checks/checks.go, score/hpa/hpa.go, score/hpa/hpa_test.go, score/hpa_test.go, score/score.go, score/testdata/hpa-has-no-target.yaml, score/testdata/hpa-targets-deployment.yaml
Fixes #162
```
RELNOTE: Add new "HorizontalPodAutoscaler has target" check that verifies that the HPA target exists (autoscaling/v1 only)
```
=> score: check that HorizontalPodAutoscaler objects targets something

cmd/kube-score/helm.Dockerfile
```
RELNOTE: update alpine to v3.10.1
```
=> docker: update alpine on the helm image to v3.10.1

score/networkpolicy/networkpolicy.go, score/networkpolicy/networkpolicy_test.go
This fixes #180
```
RELNOTE: Handle the default value of PolicyTypes in NetworkPolicies
```
=> Handle default PolicyTypes in NetworkPolicies

go.mod, go.sum
```
RELNOTE: use Kubernetes 1.17.0 API definitions
```
=> all: use Kubernetes 1.17.0 API definitions

cmd/kube-score/help_test.go, cmd/kube-score/main.go
=> cmd: detect binary name in help texts

.circleci/config.yml, .codecov.yaml
```
RELNOTE: describe the changes
```
=> ci: remove codecov integration

.goreleaser.yml
```
Add release binaries for arm and arm64
```
=> .goreleaser.yml: Add builds for arm and arm64

domain/kube-score.go, parser/internal/hpa.go, parser/parse.go, score/apps/apps.go, score/apps/apps_test.go, score/checks/checks.go, score/hpa/hpa.go, score/hpa/hpa_test.go, score/score.go
```
RELNOTE: Support HPA v2beta1 and v2beta2. All features supported by HPA v1 are supported.
```
=> Support HPA v2beta1 and v2beta2

domain/kube-score.go, parser/parse.go, score/checks/checks.go, score/ingress/ingress.go, score/ingress_test.go, score/score.go, score/testdata/ingress-networkingv1beta1-targets-service-no-match.yaml, score/testdata/ingress-networkingv1beta1-targets-service.yaml
```
RELNOTE: Added support for the networking.k8s.io/v1beta1 Ingress API
```
=> score: support Ingress networking.k8s.io/v1beta1 API

score/cronjob/cronjob.go
Very minor, like the previous one.
=> fix another typo

README.md
<p>Fix README</p>
---
This PR was created from Gustav Westling's (zegl) [workspace](https://getsturdy.com/kube-score-QEduUvS/59bce5c0-cae1-44f3-ad49-24ee3497474b) on [Sturdy](https://getsturdy.com/).
Join your team, and code and collaborate on Sturdy, [join now!](https://getsturdy.com/get-started/github).
=> docs: fix icons in README

README_CHECKS.md
<p>docs: generate  README_CHECKS.md</p>
---
This PR was created from Gustav Westling's (zegl) [workspace](https://getsturdy.com/kube-score-QEduUvS/f32ab6f4-240b-4af7-abc1-fac1bb55045a) on [Sturdy](https://getsturdy.com/).
Join your team, and code and collaborate on Sturdy, [join now!](https://getsturdy.com/get-started/github)
=> Generate README_CHECKS.md

README.md
https://github.com/Homebrew/homebrew-core/pull/88948
=> use official homebrew formula

cmd/kube-score/main.go, parser/parse.go, parser/parse_test.go, score/score_test.go
<p>parser: remove global variables</p>
---
This PR was created by Gustav Westling (zegl) on [Sturdy](https://getsturdy.com/kube-score-QEduUvS/97657f09-1e84-4d84-9226-1761a33120d3).
=> parser: remove global variables

score/apps/apps.go, score/disruptionbudget/disruptionbudget.go, score/internal/labelselector.go, score/networkpolicy/networkpolicy.go, score/score.go
<p>all: fix typo in labels</p>
---
This PR was created by Gustav Westling (zegl) on [Sturdy](https://getsturdy.com/kube-score-QEduUvS/0be4dfab-e5b4-4687-8115-910eaf5a4751).
=> all: fix typo in labels

README.md, cmd/kube-score/main.go
```
RELNOTE: Add sarif output option to documentation
```
=> Add sarif output to documentation

cmd/kube-score/main.go, go.mod, go.sum, renderer/human/human.go
Fixes https://github.com/zegl/kube-score/issues/506
=> renderer: override color support logic to add colors on GitHub Actions

score/podtopologyspreadconstraints/podtopologyspreadconstraints.go, score/podtopologyspreadconstraints_test.go, score/score.go, score/testdata/pod-topology-spread-constraints-invalid-maxskew.yaml, score/testdata/pod-topology-spread-constraints-invalid-mindomains.yaml, score/testdata/pod-topology-spread-constraints-invalid-whenunsatisfiable.yaml, score/testdata/pod-topology-spread-constraints-no-labelselector.yaml, score/testdata/pod-topology-spread-constraints-no-topologykey.yaml, score/testdata/pod-topology-spread-constraints-one-constraint.yaml, score/testdata/pod-topology-spread-constraints-two-constraints.yaml
```
RELNOTE: Add Pod Topology Spread Constraints checks
```
=> [#495] implement feature request: topologySpreadConstraints

renderer/sarif/sarif.go, sarif/sarif.go
Existing output seems not to be valid. This PR adds required fields in the output file.
Fixes #559
```
RELNOTE: Fix serif output.
```
=> Fix: create valid sarif results output file

renderer/junit/junit.go
```
RELNOTE: add description for Junit check reports
```
=> add description for JUnit test reports
