- score/container/container.go
- score/score_test.go
- score/testdata/pod-image-pullpolicy-undefined-latest-tag.yaml
- score/testdata/pod-image-pullpolicy-undefined-no-tag.yaml
A typo in the issue description that recommended the policy "PullAlways" instead of "Always" was also fixed
Fixes #39
> pullpolicy: handle containers without a explicit imagePullPolicy set

- score/service/service.go
- score/service_test.go
- score/testdata/service-externalname.yaml
> service: ignore services of type ExternalName in the service-targets-pod test

- parser/internal/deamonset.go
- parser/internal/deployment.go
- parser/internal/jobs.go
- parser/internal/statefulset.go
- score/networkpolicy_test.go
- score/testdata/networkpolicy-deployment-matching.yaml
Network policies start by checking namespace that is empty for pod inside deployments. Without this network policies tests that have namespace tests as the pod namespace is empty and the first comparison fails.
> parser: forward namespace names to pod template specs

- cmd/kube-score/.goreleaser.yml
The "archive" option is deprecated, and has been replaced by "archives"
See https://goreleaser.com/deprecations/#archive
> goreleaser: update archive configuration

- cmd/kube-score/main.go
- config/config.go
- score/container/container.go
- score/score_test.go
- score/testdata/pod-test-resources-no-limits.yaml
> allow for ignoring memory limits

- README.md
The output is generated by 'kube-score score --help'
> doc: update kube-score usage in the README

- score/apps/apps.go
Simple misspelling in some of the AntiAffinity notes.
> Misspelling: fixing beeing to being

- cmd/kube-score/main.go
- cmd/kube-score/output_test.go
- scorecard/scorecard.go
This fixes #132
```
RELNOTE: Added support for JSON output. Results in the "ci" and "human" modes are now rendered in alphabetical order. Results in "ci" mode without any comments are now always rendered.
```
> JSON output

- cmd/kube-score/main.go
- scorecard/scorecard.go
This fixes a bug introduced in #133 (never released).
> cmd: ignore ignored tests when calculating the exit code

- score/security/security.go
- score/security_test.go
- score/testdata/security-inherit-pod-security-context.yaml
This fixes #146 
```
RELNOTE: Values from PodSecurityContext are properly inherited to the container SecurityContext
```
> security: inherit values from the PodSecurityContext

- cmd/kube-score/helm.Dockerfile
The presense of ENTRYPOINT makes it unneccesarily complex to invocate helm,
which is the biggest usecase of this release mode.
```
RELNOTE: ENTRYPOINT is no longer set in the "-helm" container
```
This fixes #151
> docker: don't set ENTRYPOINT in helm based release

- cmd/kube-score/main.go
- config/config.go
- domain/kube-score.go
- score/checks/checks.go
some scores can be are rather opinionated, and it should be possible to not run them by default
```
RELNOTE: add the `--enable-optional-test` CLI flag to allow adding opt-in only scores
```
> config: allow creating optional tests

- score/container/container.go
- score/container/container_test.go
Depends on https://github.com/zegl/kube-score/pull/152
```
RELNOTE: Add optional score container-resource-requests-equal-limits for checking resource request and limits for equality
```
> Add container resource equals score

- cmd/kube-score/helm.Dockerfile
The kube-score image with helm pre-installed is shipped without the ca-certificates installed.
This causes `helm init --client-only` to fail with
```
Error: error initializing: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Get https://kubernetes-charts.storage.googleapis.com/index.yaml: x509: certificate signed by unknown authority
```
Fixed by installing the `ca-certificates` bundle.
```
RELNOTE: Added `ca-certificates` to kube-score docker image with Helm pre-installed.
```
> install ca-certificates for alpine

- cmd/kube-score/main.go
- cmd/kube-score/output_test.go
- scorecard/scorecard.go
This is a breaking change, see #164 
```
RELNOTE: remove --threshold-ok and --threshold-warning arguments
```
> cmd: remove --threshold-ok and --threshold-warning arguments

- README.md
- cmd/kube-score/main.go
- cmd/kube-score/output_test.go
- config/config.go
- parser/parse.go
- score/apps/apps.go
- score/apps/apps_test.go
- score/apps_test.go
- score/disruptionbudget/disruptionbudget.go
- score/disruptionbudget/disruptionbudget_test.go
- score/score_test.go
- scorecard/scorecard.go
By default, OK checks are hidden in the "human" output mode.
If the flag -v is set once, OK checks will be displayed.
If the flag -v is set twice, skipped checks will also be displayed.
This fixes #163
```
RELNOTE: hide OK and skipped checks by default in the "human" display mode. Set the -v flag once to display OK checks, set it twice to also display skipped checks.
```
> all: verbose output flags

- README.md
- cmd/kube-score/main.go
- cmd/kube-score/output_test.go
- go.mod
- go.sum
- score/networkpolicy/networkpolicy.go
- score/testdata/all-ok.yaml
- scorecard/scorecard.go
Use emojis to display the status of each object:
New README image:
```
RELNOTE: Display emojis after the name of each object to indicate the status. This is only affects the human output mode.
```
> Emoji headers in human output

- cmd/kube-score/main.go
- cmd/kube-score/output_test.go
Fixes #176 
Fixes #175
```
RELNOTE: Fixes for panics in the human output mode when the term size can not be detected, or was too small
```
> Prevent panic with negative string sizes

- README_CHECKS.md
- score/security/security.go
- score/security_test.go
- score/testdata/pod-seccomp-annotated.yaml
- score/testdata/pod-seccomp-no-annotation.yaml
```
RELNOTE: New check for seccomp profiles on pods. Can be enabled with 
`--enable-optional-test container-seccomp-profile`.
```
resolves #191
> score/security: optional check for seccomp annotation on pods

- cmd/kube-score/main.go
Just like kubectl and friends.
```
RELNOTE: Added shorthand argument `-o` for `--output-format`
```
> scorecard: Add -o as shorthand for --output-format

- cmd/kube-score/main.go
- renderer/ci/ci.go
- renderer/ci/ci_test.go
- renderer/human/human.go
- renderer/human/output_test.go
This will enable the kube-score.com-project [1] to use the same output mode as the CLI.
1: https://github.com/kube-score/web
> ref: create renderer packages for human and CI render modes

- README.md
- cmd/kube-score/main.go
- config/config.go
- score/score.go
- score/score_test.go
- scorecard/scorecard.go
Via new --disable-ignore-checks-annotations flag
Fixes #202 
```
RELNOTE: Allow disabling `kube-score/ignore` annotation with a new `--disable-ignore-checks-annotations` flag
```
> cmd: allow disabling kube-score/ignore annotations

- README.md
- cmd/kube-score/main.go
- renderer/json_v2/api.go
Implements a v2 JSON API behind a new `--output-version` flag. 
JSON names are now snake_case, and the top object is a list instead of a map.
As of v1.5.0  `--output-version=v1` (the default) will be deprecated. In `v1.6.0` the default will be switched to `v2`. The v1 output version will be removed in `v1.7.0`.
Fixes #186.
```
RELNOTE: Version 2 of the JSON API is now available behind the `--output-version=v2` flag. The current default (`v1`) is now deprecated, and will be removed in a future release. See the PR for more information.
```
> JSON output v2

- README.md
Not using 'kubectl get all', as it doesn't include all types of objects that kube-score might support in the future
> Document how to run kube-score against an existing Kubernetes cluster

- .goreleaser.yml
Since the LICENSE is located in the root of the repository, move the gorelease config there
Fixes #217
> release: include LICENSE file in archives

- cmd/kube-score/main.go
```
RELNOTE: use 'score' as the default sub-command when kube-score is executed as a kubectl plugin
```
Fixes #216
> cmd: use 'score' as the default sub command when executed as a kubectl plugin

- parser/error.go
- parser/parse.go
- parser/parse_test.go
- parser/testdata/invalid-yaml.yaml
- parser/testdata/valid-yaml.yaml
```
RELNOTE: descriptive error messages if input parsing fails
```
Fixes #232
> parser: propagate error if input parsing fails after type detection

- cmd/kube-score/cmd.go
- cmd/kube-score/cmd_test.go
- cmd/kube-score/main.go
This is a regression since #225 / v1.5.1
```
RELNOTE: fixes subcommand parsing which has been broken since v1.5.1
```
> cmd: fix command-line subcommand parsing

- README_CHECKS.md
- score/container/container.go
- score/container/container_test.go
- score/score_test.go
```
RELNOTE: Added new optional checks container-cpu-requests-equal-limits and container-memory-requests-equal-limits to allow for checking for CPU and memory resources separately
```
This fixes #233
> Add new optional checks for CPU and memory requests equal limits

- cmd/kube-score/main.go
As promised in #206, the release of v1.6.0 will use the v2 format by default.
See #206 for more information.
```
RELNOTE: The --output-version for JSON is now defaulting to v2. See #206 for more information.
```
> cmd: switch JSON default --output-version to v2

- cmd/kube-score/cmd.go
```
RELNOTE: Make sure that the help text is shown when kube-score is executed without subcommands
```
Fixes #254
> cmd: handle exec without a subcommand gracefully

- go.sum
- parser/internal/jobs.go
- score/networkpolicy_test.go
- score/testdata/networkpolicy-cronjob-matching.yaml
- score/testdata/networkpolicy-cronjob-not-matching-selector.yaml
- score/testdata/networkpolicy-deployment-not-matching-selector.yaml
- score/testdata/networkpolicy-statefulset-matching.yaml
- score/testdata/networkpolicy-statefulset-not-matching-selector.yaml
```
RELNOTE: Fix for CronJob parsing - This fixes issues with namespace matching of CronJob resources, for CronJobs this mostly mean that the "Pod has NetworkPolicy" test was not working.
```
> Forward CronJob Namespace properly

- .goreleaser.yml
```
RELNOTE: Publish :latest and :latest-helm tagged images to Docker Hub
```
This fixes #268
> release: publish :latest and :latest-helm

- score/security/security.go
- score/security_test.go
```
RELNOTE: correctly treat null securityContext.privileged as "false"
```
This fixes #275
> Security privileged defaults false

- .goreleaser.yml
- README.md
- cmd/kube-score/kustomize.Dockerfile
```
RELNOTE: create a new docker image for kustomize (version v3.8.1)
```
Just one difference between helm and kustomize image, on kustomize I also added git dependency because for remote bases it is necessary.
closes #273
> docker: create image for kustomize 3.8.1

- README_CHECKS.md
- score/apps/apps.go
- score/apps/apps_test.go
- score/apps_test.go
- score/score.go
- score/testdata/deployment-with-hpa-has-replicas.yaml
- score/testdata/deployment-with-hpa-not-has-replicas.yaml
```
RELNOTE: New score "Deployment targeted by HPA does not have replicas configured"
```
This closes #286
> score/apps: Deployment targeted by HPA does not have replicas configured

- README.md
- cmd/kube-score/main.go
- config/config.go
- config/semver_test.go
- score/score.go
- score/score_test.go
- score/stable/stable_version.go
- score/stable/stable_version_test.go
- score/stable_version_test.go
```
RELNOTE: Added a new --kubernetes-version flag to score. Set --kubernetes-version to the version of Kubernetes in use to tailor the recommendations to that specific version. The "Stable version" score has been modified to only recommend upgrades to APIs that are GA in the user specified version of Kubernetes.
```
This fixes #63 (at last!) 🎉
> User specified --kubernetes-version

- config/config.go
- score/stable/stable_version.go
- score/stable/stable_version_test.go
```
RELNOTE: If using Kubernetes v1.14 or later, recommend to use the networking.k8s.io/v1beta1 Ingress API instead of extensions/v1beta1
```
> score/stable: recommend Ingress networking.k8s.io/v1beta1

- score/networkpolicy/networkpolicy.go
- score/networkpolicy_test.go
- score/testdata/networkpolicy-targets-all-pods.yaml
This is done by adopting the Kubernetes-provided metav1.LabelSelector, as is already used by the networkpolicy-targets-pod test.
```
RELNOTE: Support empty podSelectors in the "Pod has NetworkPolicy" test
```
This fixes #293
> score/networkpolicy: handle empty podSelector properly in the pod-has-networkpolicy test

- cmd/kube-score/main.go
- parser/parse.go
- parser/parse_test.go
- renderer/sarif/sarif.go
- sarif/sarif.go
- score/filelocation_test.go
- score/testdata/helm/app1/Chart.yaml
- score/testdata/helm/app1/templates/deployment.yaml
- score/testdata/linenumbers-helm.yaml
- score/testdata/linenumbers.yaml
```
RELNOTE: Add support for the [SARIF](https://sarifweb.azurewebsites.net/) output format (`--output-format sarif`). This API is considered to be in Alpha.
```
The support is fairly basic, but it works!
Here's a screenshot of the SARIF Viewer in VS Code, using a SARIF-file generated from some of kube-scores testdata:
```bash
kube-score score -o sarif \
score/testdata/deployment-host-antiaffinity-preffered-selector-expression.yaml \
score/testdata/deployment-poddisruptionbudget-expression-matches.yaml > output.sarif
```
> SARIF output format

- go.sum
- score/probe_test.go
- score/probes/probes.go
- score/probes/probes_test.go
- score/testdata/pod-probes-not-targeted-by-service-multi-labels.yaml
- score/testdata/pod-probes-targeted-by-service-same-namespace-multi-labels.yaml
Previously only one label needed to match and not all, causing false positives
```
RELNOTE: Fix a bug in the "Pod Probes" test where a Pod could incorrectly be considered to be targeted by a Service
```
This fixes #316
> probes: correctly check if a pod is targeted by a service

- README_CHECKS.md
- score/apps/apps.go
- score/apps/apps_test.go
- score/apps_test.go
- score/score.go
- score/testdata/statefulset-service-name-different-label.yaml
- score/testdata/statefulset-service-name-different-name.yaml
- score/testdata/statefulset-service-name-different-namespace.yaml
- score/testdata/statefulset-service-name-not-headless.yaml
- score/testdata/statefulset-service-name.yaml
```
RELNOTE: Validate serviceName of a StatefulSet 
```
This PR closes #315 
This adds `statefulset-has-servicename` that checks following rules:
- StatefulSets `.spec.serviceName` matches a Service in the same namespace.
- The Service is a Headless Service.
> StatefulSets currently require a Headless Service to be responsible for the network identity of the Pods. You are responsible for creating this Service.
https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#limitations
- The Service has a selector that matches the StatefulSet.
> score/apps: StatefulSets should have a valid headless serviceName 

- .goreleaser.yml
- README.md
- cmd/kube-score/helm3.Dockerfile
… seperate kube-score:<tag>-helm3, updated readme for docker run example to v1.10.0 to match current version.
```
RELNOTE: added support for helm v3 and created new dockerfile and tagging.  eg. docker pull zegl/kube-score:v1.10.0-helm3
```
> Helmv3 Support

- score/apps/apps.go
- score/apps/apps_test.go
- score/apps_test.go
- score/security_test.go
- score/testdata/networkpolicy-statefulset-matching.yaml
- score/testdata/networkpolicy-statefulset-not-matching-selector.yaml
- score/testdata/statefulset-appsv1beta1.yaml
- score/testdata/statefulset-appsv1beta2.yaml
- score/testdata/statefulset-different-labels.yaml
- score/testdata/statefulset-host-antiaffinity-1-replica.yaml
- score/testdata/statefulset-host-antiaffinity-not-set.yaml
- score/testdata/statefulset-host-antiaffinity-preffered.yaml
- score/testdata/statefulset-host-antiaffinity-required.yaml
- score/testdata/statefulset-host-antiaffinity-undefined-replicas.yaml
- score/testdata/statefulset-poddisruptionbudget-v1beta1-expression-matches.yaml
- score/testdata/statefulset-poddisruptionbudget-v1beta1-expression-no-match.yaml
- score/testdata/statefulset-poddisruptionbudget-v1beta1-matches.yaml
- score/testdata/statefulset-poddisruptionbudget-v1beta1-no-match.yaml
- score/testdata/statefulset-service-name-different-label.yaml
- score/testdata/statefulset-service-name-different-name.yaml
- score/testdata/statefulset-service-name-different-namespace.yaml
- score/testdata/statefulset-service-name-not-headless.yaml
- score/testdata/statefulset-service-name.yaml
Based on https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#pod-selector
This fixes #336
```
RELNOTE: Add StatefulSet selector labels check
```
> score/apps: fix statefulset selector labels check

- README_CHECKS.md
- score/apps/apps.go
- score/apps/apps_test.go
- score/internal/labelselector.go
Adding support for MatchExpressions in the StatefulSet selector test as well
This fixes #382
```
RELNOTE: Add Deployment selector labels check
```
> score: add test for deployment selector matching the pod template labels

- README_CHECKS.md
- score/score_test.go
- score/security/security.go
- score/security_test.go
```
RELNOTE: As announced in v1.10.0: `container-security-context` is now disabled by default (is now opt-in, and will be removed in v1.13.0), The new checks container-security-context-user-group-id, container-security-context-privileged and container-security-context-readonlyrootfilesystem are now enabled by default. See SECURITYCONTEXT.md for more.
```
> score: flip Container Security Context checkst

- .circleci/config.yml
- cmd/kube-score/helm.Dockerfile
- cmd/kube-score/helm3.Dockerfile
```
RELNOTE: Upgrade alpine to 3.14.2. Upgrade Go to 1.17. Upgrade Helm 2 to v2.17.0. Upgrade Helm 3 to v3.6.3.
```
> Upgrade Go, Alpine, and Helm dependencies

- parser/internal/ingress.go
- score/ingress_test.go
- score/testdata/ingress_issue388.yaml
Fixes #388
```
RELNOTE: Fix panic for Ingresses with empty http blocks . This affected the `networking/v1beta1` and `extensions/v1beta1` versions of Ingress.
```
> Do not panic on empty http block in ingress

- domain/kube-score.go
- parser/internal/pdb/pod.go
- parser/parse.go
- score/checks/checks.go
- score/disruptionbudget/disruptionbudget.go
- score/poddisruptionbudget_test.go
- score/score.go
- score/testdata/deployment-poddisruptionbudget-v1-no-policy.yaml
- score/testdata/deployment-poddisruptionbudget-v1beta1-no-policy.yaml
This adds check for PodDisruptionBudget with no policy. PDBs should specify a policy with `minAvailable` or `maxUnavailable`. This test flags PDBs that don't specify either.
This is based on the assumption that the PDB is invalid without `minAvailable` or `maxUnavailable` defined -- do you know of any cases where it's valid to not specify either? I don't. When I've tested a PDB like this in k8s (by accident 😄), the controller sets `.status.expectedPods: 0` regardless of the deployment replicas field.
```
RELNOTE: Add check for PodDisruptionBudget with no policy
```
> score: add check for PodDisruptionBudget with no policy

- cmd/kube-score/helm3.Dockerfile
<p>cmd: upgrade Helm3 to v3.7.0</p><p>This fixes <a target="_blank" rel="noopener noreferrer nofollow" href="https://github.com/zegl/kube-score/issues/394">https://github.com/zegl/kube-score/issues/394</a></p>
```
RELNOTE: Upgrade Helm3 to v3.7.0
```
---
This PR was created from Gustav Westling's (zegl) [workspace](https://getsturdy.com/kube-score-QEduUvS/f32ab6f4-240b-4af7-abc1-fac1bb55045a) on [Sturdy](https://getsturdy.com/).
Join your team, and code and collaborate on Sturdy, [join now!](https://getsturdy.com/get-started/github)
> Upgrade Helm

- score/apps/apps.go
- score/apps/apps_test.go
<p>score/apps: support more topology keys</p><p>Adds support for additional “approved” topology keys in the hasPodAntiAffinity score</p>
Fixes #390
```
RELNOTE: Add support for more topology kets in the hasPodAntiAffinity test
```
---
This PR was created from Gustav Westling's (zegl) [workspace](https://getsturdy.com/kube-score-QEduUvS/ec482ab3-1b84-47fc-8b77-3974d49c7dbb) on [Sturdy](https://getsturdy.com/).
Join your team, and code and collaborate on Sturdy, [join now!](https://getsturdy.com/get-started/github)
> score/apps: support more topology keys

- score/stable/stable_version.go
- score/stable/stable_version_test.go
<p>score/stable: recommend usage of networking.k8s.io/v1</p><p></p><pre><code>RELNOTE: Recommend networking.k8s.io/v1 instead of the deprecated networking.k8s.io/v1beta1 APIs.
</code></pre><p><br>Fixes <a target="_blank" rel="noopener noreferrer nofollow" href="https://github.com/zegl/kube-score/issues/415">#415</a></p>
---
This PR was created from Gustav Westling's (zegl) [workspace](https://getsturdy.com/kube-score-QEduUvS/ec482ab3-1b84-47fc-8b77-3974d49c7dbb) on [Sturdy](https://getsturdy.com/).
Join your team, and code and collaborate on Sturdy, [join now!](https://getsturdy.com/get-started/github)
> Add Stable check for Ingress

- score/apps/apps.go
- score/security/security.go
- scorecard/scorecard.go
I experimented a bit with various linters from https://golangci-lint.run/ and found a couple of fairly trivial things to fix/optimize.
`strings.EqualFold` is quite a bit faster compared than using `toLower()` https://hackernoon.com/optimizing-string-comparisons-in-go-7h1b3udm 
I'm not sure how you feel about sorting go imports.
In `score/score_test.go` this bit is marked as dead code.
```
type unnamedReader struct {
io.Reader
}
func (unnamedReader) Name() string {
return ""
}
```
Thanks for a neat tool :tada:
> Simplified boolean checks and case-insensitive string comparison.

- score/container/container.go
- score/score_test.go
- score/testdata/pod-container-ports-duplicate-names.yaml
- score/testdata/pod-container-ports-missing-containerport.yaml
- score/testdata/pod-container-ports-ok.yaml
```
RELNOTE: Implements an optional Pod container ports test. Checks to ensure a ports containerPort value isn't missing and name ports are unique.
```
> Fixes: missing containerPort not detected #416

- .gitignore
- go.mod
- go.sum
```
Bump golang.org/x/crypto from v0.0.0-20200622213623-75b288015ac9 to v0.0.0-20201216223049-8b5274cf687f (fixes CVE-2020-29652)
Added to ignored files "coverage.txt", generated during execution of tests
```
> Updated crypto module to get rid of vulnerability

- .circleci/config.yml
- .golangci.yml
- cmd/kube-score/help_test.go
- cmd/kube-score/main.go
- config/semver_test.go
- parser/parse.go
- renderer/human/human.go
- renderer/json_v2/api.go
- score/checks/checks.go
- score/container/container.go
- score/container/container_test.go
- score/disruptionbudget/disruptionbudget.go
- score/disruptionbudget/disruptionbudget_test.go
- score/filelocation_test.go
- score/hpa/hpa_test.go
- score/meta/labels_test.go
- score/networkpolicy/networkpolicy.go
- score/networkpolicy/networkpolicy_test.go
- score/score_test.go
- score/stable/stable_version_test.go
- scorecard/scorecard.go
There are some commented out linters that create a fair share of warnings, e.g., `govet`. Don't know how you feel about fixing the warnings from them, before merging.
> Introduce golangci-lint

- .golangci.yml
- cmd/kube-score/main.go
- go.mod
- go.sum
- parser/error.go
- parser/parse.go
- renderer/human/human.go
- renderer/human/output_test.go
- score/filelocation_test.go
- score/score_test.go
- score/stable/stable_version.go
- score/stable/stable_version_test.go
- score/stable_version_test.go
This enables the last four linters left out from #438 Tests currently fail, and I'll try to fix them today. See #440 for reference.
While doing this, I had a look at `go.mod` Are you sure 1.13 will work with the current code?
> Enable more linters in CI.

- README_CHECKS.md
- go.mod
- go.sum
- score/container/container.go
- score/score_test.go
- score/testdata/pod-env-duplicated.yaml
- score/testdata/pod-env-ok.yaml
score/container: To detect duplicate defined environment variables.
Fixes #448
```
$ ./kube-score score ~/test.yaml 
apps/v1/Deployment sample-deployment                                          💥
[CRITICAL] Environment Variable Key Duplication
· sampleA -> Environment Variable Key Duplication
Container environment variable key 'SAMPLE_ENV_VAR' duplicated
· sampleB -> Environment Variable Key Duplication
Container environment variable key 'SAMPLE_ENV_VAR1' duplicated
· sampleB -> Environment Variable Key Duplication
Container environment variable key 'SAMPLE_ENV_VAR2' duplicated
```
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
name: sample-deployment
labels:
app: sample
annotations:
kube-score/ignore: pod-networkpolicy,container-resources,container-image-pull-policy,container-sec …
```
> Implement feature request: To detect duplicate defined environment variables

- README.md
- cmd/kube-score/main.go
- config/config.go
- score/checks/checks.go
- score/score.go
- score/score_test.go
- score/security_test.go
- score/testdata/pod-container-ports-missing-containerport-annotation-optional.yaml
- score/testdata/pod-ephemeral-storage-request-nomatch-limit-annotation-optional.yaml
- score/testdata/pod-seccomp-annotated-annotation-optional.yaml
- score/testdata/pod-test-resources-no-limits-annotation-optional.yaml
- scorecard/scorecard.go
Fixes: #476
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
name: optional-test-manifest-deployment
labels:
app: optional-test-manifest
annotations:
kube-score/ignore: pod-networkpolicy,container-resources,container-image-pull-policy,container-security-context-privileged,container-security-context-user-group-id,container-security-context-readonlyrootfilesystem,container-ephemeral-storage-request-and-limit
kube-score/optional: container-seccomp-profile
spec:
replicas: 1
selector:
matchLabels:
app: optional-test-manifest
template:
metadata:
labels:
app: optional-test-manifest
spec:
containers:
- name: optional-test-manifest
image: busybox:1.34
command:
- /bin/sh
- -c
- date; env; tail -f /dev/null
```
```
$ kube-score score manifest.yaml
apps/v1/Deployment …
```
> Implement feature request: Annotation in the manifest can be used to specify optional

- parser/parse.go
- score/apps_test.go
- score/score.go
- score/score_test.go
- score/security_test.go
- score/testdata/statefulset-nested-ignores.yaml
- scorecard/enabled.go
- scorecard/scorecard.go
```
RELNOTE: Adds support for the kube-score/ignore and kube-score/enable annotation on child resources such as Deployment and StatefulSet Pod Templates. The "child" annotations will override an annotations set on the root object.
```
Fixes #488
> score: allow ignore/allow annotations on child template resources

- bors.toml
We don't really need bors anymore. Let's move back to the default GitHub workflows.
> bors: remove

- scorecard/enabled.go
> scorecard: trim whitespace in annotation keys

- score/score_test.go
- score/testdata/kube-score-ignore-annotations.yaml
- scorecard/enabled.go
Fixes #542
```
RELNOTE: Fix bug related to processing implied kube-score/ignore annotations.
```
> Ignoring rule container resources makes every rule exceptional #542

- cmd/kube-score/main.go
- parser/parse.go
- renderer/ci/ci_test.go
- renderer/human/output_test.go
```
RELNOTE: describe the changes
```
> chore: remove refs to deprecated io/ioutil

- renderer/human/human.go
> renderer/human: show file names in case of error or warning

- score/container/container.go
The `container-resources` check adds comments for missing requests even if limits are missing.
The `container-ephemeral-storage-request-and-limit` check omits the request check comment if a limit is missing.
This PR will add a comment for both issues (limit and request) if both checks apply.
> Align `container-ephemeral-storage-request-and-limit` to `container-resources`

- .github/workflows/test.yaml
- Dockerfile
- README.md
- go.mod
* update Go version due to 1.19 support has already ended
* https://endoflife.date/go
* to CI run using multiple Go versions and OS types
* doc fix
> ci/go: bump Go version from 1.19 to 1.21 and fix CI style

- score/probes/probes.go
```
RELNOTE: Pod Probes: correctly mark check as skipped when Pod is not targeted by a Service
```
> score/probes: set score.Skipped if pod not targeted by service

- go.mod
- score/deployment/deployment.go
- score/deployment_test.go
- score/score.go
- score/testdata/hpa-target-deployment.yaml
- score/testdata/service-target-deployment-not-rolling.yaml
- score/testdata/service-target-deployment-replica-1.yaml
- score/testdata/service-target-deployment-strategy-not-set.yaml
Fixes #569
Fixes #570
```
RELNOTE: Adding Deployment checks verifying if update strategy and replicas are correct
```
> Add deployment checks

- score/optional_test.go
- score/testdata/pod-container-memory-requests-annotation-optional.yaml
- score/testdata/pod-container-memory-requests.yaml
- scorecard/enabled.go
Fixes #582
```
RELNOTE: fixes a bug where tests enabled with `--enable-optional-test` where still skipped
```
> scorecard: fix enabling of optional tests with CLI flag

- domain/kube-score.go
- parser/internal/hpa.go
- score/apps/apps_test.go
- score/deployment/deployment.go
- score/deployment_test.go
- score/hpa/hpa.go
- score/hpa/hpa_test.go
- score/hpa_test.go
- score/score_test.go
- score/testdata/hpa-min-replicas-nok.yaml
- score/testdata/hpa-min-replicas-ok.yaml
- Added a check for min replicas > 1 for HorizontalPodAutoscalers
- Clarified the comment if a deployment replica check was skipped
Fixes #581
```
RELNOTE: score/hpa: added a check for hpa min replicas > 1
```
> score/hpa: added a check for hpa min replicas > 1

- cmd/kube-score/main.go
- config/config.go
- domain/kube-score.go
- examples/custom_check.go
- examples/custom_check_test.go
- parser/parse.go
- parser/parse_test.go
- renderer/sarif/sarif.go
- score/apps_test.go
- score/checks/checks.go
- score/container/container.go
- score/deployment_test.go
- score/filelocation_test.go
- score/optional_test.go
- score/score.go
- score/score_test.go
- score/security_test.go
- score/stable_version_test.go
- scorecard/scorecard.go
Refactor/rewrite the Go API (not previously considered to be stable) to be extendable with custom checks written in Go, and to make the API easier to consume.
The API is not yet considered to be stable, but this is a good step in that direction.
Fixes #534
> all: extendable externally usable API

- score/internal/labelselector.go
`apimachinery` has defined a [Lookup-Method](https://pkg.go.dev/k8s.io/apimachinery@v0.34.0/pkg/labels#Labels) for the `Labels` interface starting from `0.34.0`.
We are using kubescore as a dependency in [our go code](https://github.com/steadybit/extension-kubernetes) and want to use the latest version of `apimachinery`.
This PR is adding this method (without increasing the version of `apimachinery`)
This would also make dependabot happy (#675)
> prepare for `apimachinery` >= 0.34
